name: 'Cargar Datos CSV a MySQL'

on:
  # Permite ejecutar este workflow manualmente desde la pestaña "Actions"
  workflow_dispatch:
    inputs:
      csv_file:
        description: 'Nombre del archivo CSV a cargar'
        required: true
        default: 'ai_job_dataset.csv'
      table_name:
        description: 'Nombre de la tabla de destino en la BD'
        required: true
        default: 'jobs'

jobs:
  load-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas mysql-connector-python
      - name: Run create and load script
        # Asegúrate de que tu script se llame 'crear_y_cargar.py'
        run: python crear_y_cargar.py
        env:
          # Lee los valores de los inputs y los secretos
          CSV_FILENAME: ${{ github.event.inputs.csv_file }}
          TABLE_NAME: ${{ github.event.inputs.table_name }}
          DB_HOST: ${{ secrets.DB_HOST }} # La IP se lee desde los secretos
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}